apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-server-serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
# Usando Role para acesso restrito ao namespace 'dev'
kind: Role
# Usando ClusterRole para permitir acesso em múltiplos namespaces
# kind: ClusterRole 
metadata:
  name: go-server-serviceaccount-read
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
# Usando RoleBinding para associar ao namespace 'dev'
kind: RoleBinding
# kind: ClusterRoleBinding # Usando ClusterRoleBinding para associar em múltiplos
metadata:
  name: go-server-serviceaccount-read-binding
subjects:
- kind: ServiceAccount
  name: go-server-serviceaccount
  namespace: dev
roleRef:
  kind: Role
  name: go-server-serviceaccount-read
  apiGroup: rbac.authorization.k8s.io